version: '3.7'

services:
  shpmnt_app:
    container_name: shpmnt_laravel_app
    hostname: shpmnt_laravel_app
    restart: unless-stopped
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
        TIMEZONE: ${TIMEZONE}
        RUN_QUEUE: ${RUN_QUEUE}
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./project:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - shpmnt-mysql
      - shpmnt-nginx

  shpmnt_nginx:
    container_name: shpmnt_laravel_nginx
    hostname: shpmnt_laravel_nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:8080
      - 443:8443
    volumes:
      - ./project:/var/www
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shpmnt-nginx
    depends_on:
      - shpmnt_app

  shpmnt_db:
    image: mysql:5.7
    container_name: shpmnt_laravel_db
    hostname: shpmnt_laravel_db
    restart: unless-stopped
    volumes:
      - shpmnt_backend_mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - shpmnt-mysql

networks:
  shpmnt-mysql:
    name: shpmnt_backend_laravel-mysql_net
    driver: bridge
  shpmnt-nginx:
    name: shpmnt_backend_laravel-nginx_net
    driver: bridge

volumes:
  shpmnt_backend_mysql:
    name: shpmnt_backend_mysql_vol
    driver: local
